language: python
python:
  - "2.7"
  # - "3.6"

install:
  - pip install -r requirements.txt

script:
  - zip deploy/app.zip application.py

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "beanstalk"
  env: "dev"
  bucket_name: $S3_BUCKET
  zip_file: deploy/app.zip
  skip_cleanup: true
